#!/usr/bin/env bash
#CommentFor.
#!/usr/bin/env bash

for i in {1..100}; do
    # compute modulo
    mod3=$(( i % 3 ))
    mod5=$(( i % 5 ))

    case "$mod3$mod5" in
        00)  # divisible by 3 AND 5
            echo "FizzBuzz"
            ;;
        0*)  # divisible by 3
            echo "Fizz"
            ;;
        *0)  # divisible by 5
            echo "Buzz"
            ;;
        *)   # anything else
            echo "$i"
            ;;
    esac
done

##!/usr/bin/env bash
## FizzBuzz 1..100

#for i in {1..100}; do
    #if (( i % 3 == 0 && i % 5 == 0 )); then
    #    echo "FizzBuzz"
   # elif (( i % 3 == 0 )); then
     #   echo "Fizz"
    #elif (( i % 5 == 0 )); then
    #    echo "Buzz"
   # else
  #      echo "$i"
 #   fi
#done
