#!/usr/bin/env bash
# Display "Best School" 10 times, but on the 9th iteration also print "Hi"

count=1
var="Best School"

while [ $count -le 10 ]; do
    echo "$var"
    
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    
    ((count++))
done
