#!/usr/bin/env bash
#Clock loop
hours=0
minutes=0

echo "Hour: $hours"

while true; do
    ((minutes++))

    if [ "$minutes" -ge 60 ]; then
        ((hours++))
        ((minutes = 0))
        echo "Hour: $hours"
    else
        echo "$minutes"
    fi

    # Break AFTER printing 12:59
    if [ "$hours" -eq 12 ] && [ "$minutes" -eq 59 ]; then
        break
    fi

    # Prevent going to hour 13
    if [ "$hours" -ge 13 ]; then
        break
    fi
done
