#!/usr/bin/env bash
#If...
if [ -e school ]; then
    echo "school file exists"

    # check if empty
    if [ ! -s school ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # check if regular file
    if [ -f school ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi

