#!/usr/bin/env bash
# This script creates a PID file, prints indefinitely, and handles signals properly.

# Create PID file
echo $$ > /var/run/myscript.pid

# SIGTERM handler
term_handler() {
    echo "I hate the kill command"
    rm -f /var/run/myscript.pid
    exit 0
}

# SIGINT handler
int_handler() {
    echo "Y U no love me?!"
}

# SIGQUIT handler
quit_handler() {
    rm -f /var/run/myscript.pid
    exit 0
}

trap term_handler SIGTERM
trap int_handler SIGINT
trap quit_handler SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done

