#!/usr/bin/env bash
#What?
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit 0' SIGQUIT SIGTERM
pgrep 10-process_and_pid_file > /var/run/myscript.pid
chmod 777 /var/run/myscript.pid
chmod +t /var/run
chmod +t /var
while true; do 
     echo "To infinity and beyond"
     sleep 2     
done

     
